### ISSUE TITLE
bug: Better error handling reporting when encountering 500 errors agains GraphQL endpoint

### ISSUE THREAD

**Issue by FragmentedPacket** [opsmill/infrahub#5513]
h3.  Component

[| #component]

API Server / GraphQL, Frontend UI

h3.  Infrahub version

[| #infrahub-version]

1.1.3

h3.  Current Behavior

[| #current-behavior]

We encountered an error when attempting to generate an artifact where we passed in the wrong variable to the GraphQL query in our artifact definition.

This also shows the task completed, but it actually failed:

[!https://github.com/user-attachments/assets/4e7083af-01af-4a42-b361-56160c5c29cd!| https://github.com/user-attachments/assets/4e7083af-01af-4a42-b361-56160c5c29cd]

If we navigate to the link provided in the 502, we can see the error message:

[!https://github.com/user-attachments/assets/598bb666-bf02-47b0-a2b1-7b444a77554e!| https://github.com/user-attachments/assets/598bb666-bf02-47b0-a2b1-7b444a77554e]

h3.  Expected Behavior

[| #expected-behavior]

Return the message of the error that may provide more insight to the user rather than the traceback. Also, properly fail the task.

h3.  Steps to Reproduce

[| #steps-to-reproduce]

# `invoke demo.start`
# Create a group called `AllDevices`
# Add read-only repo: [https://github.com/FragmentedPacket/infrahub-artifact-test| https://github.com/FragmentedPacket/infrahub-artifact-test]
# Change the parameter on the artifact definition from `hostname` to `device`
# Create a device `router1` with an interface
# Add device to `AllDevices`
# Regenerate the artifact and check the task

h3.  Additional Information

[| #additional-information]

_No response_

**Comment by ogenstad** [comment]
@FragmentedPacket is this fixed by https://github.com/opsmill/infrahub/pull/7209/files and https://github.com/opsmill/infrahub/pull/7134?

**Comment by FragmentedPacket** [comment]
No, this still occurs with custom build off the latest stable.

```
Encountered exception during execution: HTTPStatusError("Server error '502 Bad Gateway' for url 'http://server:8000/api/query/interface_query?branch=main&update_group=true&subscribers=18658f7f-9c7b-1929-30da-c5125c120bef'\nFor more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/502") Traceback (most recent call last): File "/usr/local/lib/python3.12/site-packages/prefect/flow_engine.py", line 1359, in run_context yield self File "/usr/local/lib/python3.12/site-packages/prefect/flow_engine.py", line 1421, in run_flow_async await engine.call_flow_fn() File "/usr/local/lib/python3.12/site-packages/prefect/flow_engine.py", line 1373, in call_flow_fn result = await call_with_parameters(self.flow.fn, self.parameters) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/source/backend/infrahub/git/tasks.py", line 291, in generate_artifact result = await repo.render_artifact(artifact=artifact, artifact_created=artifact_created, message=model) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/source/backend/infrahub/git/integrator.py", line 1365, in render_artifact response = await self.sdk.query_gql_query( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/source/python_sdk/infrahub_sdk/client.py", line 1149, in query_gql_query resp.raise_for_status() File "/usr/local/lib/python3.12/site-packages/httpx/_models.py", line 763, in raise_for_status raise HTTPStatusError(message, request=request, response=self) httpx.HTTPStatusError: Server error '502 Bad Gateway' for url 'http://server:8000/api/query/interface_query?branch=main&update_group=true&subscribers=18658f7f-9c7b-1929-30da-c5125c120bef' For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/502
```

**Comment by saltas888** [comment]
Consolidating into #6184, same root cause: parameters defined for a definition in `.infrahub.yml` are never validated against the query's variables at import time, so the mismatch only surfaces at runtime as a raw 502 from `/api/query`. #6184 hits it through a generator definition, this one through an artifact definition, both go through the same import and `query_gql_query` execution path, one fix covers both.

One sub-symptom from here worth keeping in mind over there: the artifact task could report Completed while the generation actually failed (original screenshot). The 2025-09 retest traceback suggests the flow now raises instead, worth re-checking when the fix lands.
